---

- name: run containers
 
  tasks:
  - name: copy docker file
    copy:
      src: docker-compose.yml
      dest: docker-compose.yml
  - name: dockercompose
    shell: 
      cmd: docker-compose up
